// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probePacketKeyT struct {
	_     structs.HostLayout
	SrcIp struct {
		_      structs.HostLayout
		S_addr uint32
	}
	DstIp struct {
		_      structs.HostLayout
		S_addr uint32
	}
	SrcPort uint16
	DstPort uint16
	Seq     uint32
	Pad     uint32
}

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	DropRetransmit         *ebpf.ProgramSpec `ebpf:"drop_retransmit"`
	FentryTcpRetransmitSkb *ebpf.ProgramSpec `ebpf:"fentry_tcp_retransmit_skb"`
	FexitTcpRetransmitSkb  *ebpf.ProgramSpec `ebpf:"fexit_tcp_retransmit_skb"`
	RedirectToLoopback     *ebpf.ProgramSpec `ebpf:"redirect_to_loopback"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	RetrPacketMap  *ebpf.MapSpec `ebpf:"retr_packet_map"`
	RetransmitPipe *ebpf.MapSpec `ebpf:"retransmit_pipe"`
	TransmitPipe   *ebpf.MapSpec `ebpf:"transmit_pipe"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
	MatchIp   *ebpf.VariableSpec `ebpf:"match_ip"`
	MatchPort *ebpf.VariableSpec `ebpf:"match_port"`
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	RetrPacketMap  *ebpf.Map `ebpf:"retr_packet_map"`
	RetransmitPipe *ebpf.Map `ebpf:"retransmit_pipe"`
	TransmitPipe   *ebpf.Map `ebpf:"transmit_pipe"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.RetrPacketMap,
		m.RetransmitPipe,
		m.TransmitPipe,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
	MatchIp   *ebpf.Variable `ebpf:"match_ip"`
	MatchPort *ebpf.Variable `ebpf:"match_port"`
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	DropRetransmit         *ebpf.Program `ebpf:"drop_retransmit"`
	FentryTcpRetransmitSkb *ebpf.Program `ebpf:"fentry_tcp_retransmit_skb"`
	FexitTcpRetransmitSkb  *ebpf.Program `ebpf:"fexit_tcp_retransmit_skb"`
	RedirectToLoopback     *ebpf.Program `ebpf:"redirect_to_loopback"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.DropRetransmit,
		p.FentryTcpRetransmitSkb,
		p.FexitTcpRetransmitSkb,
		p.RedirectToLoopback,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfeb.o
var _ProbeBytes []byte
